## 尚未解决的Bug
- 测试文件: /home/cmcandy/code/PD/Paddle/test/legacy_test/test_fake_quantize_op.py


```cpp
TestFakeQuantizeRangeAbsMaxOp
....

def test_fake_quantize_range_abs_max(self):
        dtype_options = [np.float16, np.float32]
        is_test_options = [False, True]
        # is_test_options = [False]
        round_type_options = ['TiesToEven', 'TiesAwayFromZero']
        for dtype, is_test, round_type in itertools.product(
            dtype_options, is_test_options, round_type_options
        ):
            print("[dtype, is_test, round_type]:", dtype, is_test, round_type)
            self.attrs['bit_length'] = 8 if is_test else 5
            with self.subTest(
                dtype=dtype, is_test=is_test, round_type=round_type
            ):
                self._fake_quantize_range_abs_max(
                    dtype,
                    (8, 16, 6, 6),
                    lambda shape: (np.random.random(shape) - 0.4) * 10,
                    is_test=is_test,
                    round_type=round_type,
                )


```
- 错误分析:**当is_test设为true的时候,会报错**,完整log参考此文件:[test6.log](./test6.log)
- 主要分为下面两类:
```cpp
======================================================================
ERROR: test_fake_quantize_range_abs_max (__main__.TestFakeQuantizeRangeAbsMaxOp) (dtype=<class 'numpy.float16'>, is_test=True, round_type='TiesToEven')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/legacy_test/test_fake_quantize_op.py", line 244, in test_fake_quantize_range_abs_max
    self._fake_quantize_range_abs_max(
  File "test/legacy_test/test_fake_quantize_op.py", line 229, in _fake_quantize_range_abs_max
    self.check_output(check_dygraph=False)
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2793, in check_output
    res = self.check_output_with_place(
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2643, in check_output_with_place
    static_checker.check()
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2213, in check
    self.calculate_output()
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2221, in calculate_output
    outs, fetch_list = self.op_test._calc_output(
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 1597, in _calc_output
    outs = executor.run(
  File "/home/cmcandy/.local/lib/python3.8/site-packages/paddle/base/executor.py", line 1789, in run
    res = self._run_impl(
  File "/home/cmcandy/.local/lib/python3.8/site-packages/paddle/base/executor.py", line 1995, in _run_impl
    ret = new_exe.run(
  File "/home/cmcandy/.local/lib/python3.8/site-packages/paddle/base/executor.py", line 833, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:


    PreconditionNotMetError: Tensor holds no memory. Call Tensor::mutable_data firstly.
      [Hint: holder_ should not be null.] (at /home/cmcandy/code/PD/Paddle/paddle/phi/core/dense_tensor_impl.cc:41)
      [operator < pd_kernel.phi_kernel > error]


======================================================================
FAIL: test_fake_quantize_range_abs_max (__main__.TestFakeQuantizeRangeAbsMaxOp) (dtype=<class 'numpy.float32'>, is_test=True, round_type='TiesToEven')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/legacy_test/test_fake_quantize_op.py", line 244, in test_fake_quantize_range_abs_max
    self._fake_quantize_range_abs_max(
  File "test/legacy_test/test_fake_quantize_op.py", line 229, in _fake_quantize_range_abs_max
    self.check_output(check_dygraph=False)
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2793, in check_output
    res = self.check_output_with_place(
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2643, in check_output_with_place
    static_checker.check()
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2213, in check
    self.calculate_output()
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 2221, in calculate_output
    outs, fetch_list = self.op_test._calc_output(
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 1604, in _calc_output
    self._check_ir_output(place, program, feed_map, fetch_list, outs)
  File "/home/cmcandy/code/PD/Paddle/test/legacy_test/op_test.py", line 1504, in _check_ir_output
    check_method(
  File "/home/cmcandy/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 985, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/cmcandy/anaconda3/envs/torch-py8/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/cmcandy/.local/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
Operator Check (fake_quantize_range_abs_max) has diff at Place(cpu)
Expect   - shape: [1]
  - layout: NCHW
  - place: Place(cpu)
  - dtype: float32
  - data: [5.99835]
But Got  - shape: []
  - layout: NCHW
uninited
 in class TestFakeQuantizeRangeAbsMaxOp
(shapes (1,), (0,) mismatch)
 x: array([5.998346], dtype=float32)
 y: array([], dtype=float64)

```
- 看了一下compute的逻辑在:
    - /home/cmcandy/code/PD/Paddle/paddle/fluid/operators/fake_quantize_op.h

```cpp
template <typename T, typename DeviceContext>
class FakeQuantizeRangeAbsMaxKernel : public framework::OpKernel<T> {
 public:
  void Compute(const framework::ExecutionContext &context) const override {
    .....
    // testing
    if (is_test) {
        ClipAndFakeQuantFunctor<DeviceContext, T>()(
            dev_ctx, *in, *in_scale, bin_cnt, round_type, out);
        return;
    }
    .....
  }};
```
- 疑问:不知到有没有遇到过类似问题